services:
  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    networks:
      - pgvector-net

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@pgvector:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - pgvector
    networks:
      - pgvector-net

volumes:
  pgvector-data:

networks:
  pgvector-net:
    driver: bridge