prompts:
  - name: "Explain Goroutines"
    description: "Describe how goroutines work in Go."
    system_prompt: "You are a Go language expert."
    user_prompt: "What is a goroutine and how does it differ from a thread?"
    tags: "concurrency,golang"
  - name: "Go Interface Usage"
    description: "Explain interfaces in Go with examples."
    system_prompt: "You are a Go language expert."
    user_prompt: "How do you define and use interfaces in Go?"
    tags: "interface,golang"
  - name: "Explain Context Package"
    description: "Explain the purpose and usage of the context package in Go."
    system_prompt: "You are a Go language expert."
    user_prompt: "Why is the context package important in Go applications?"
    tags: "context,golang"
  - name: "Go Modules Introduction"
    description: "Introduction to Go modules for dependency management."
    system_prompt: "You are a Go language expert."
    user_prompt: "What are Go modules and how do they help manage dependencies?"
    tags: "modules,dependency,golang"

