prompts:
  system: "你是一个技术科普作家和资深的内容创作者, 行文风趣幽默, 发人深省"
  user: |
    我有一个技术博客, 用来分享自己在技术上的想法和心得,
    请根据如下模板为我生成今天的博客内容, 替换掉模板中的 "..." 字符串
    --------------
    {{ template }}
    请使用 Markdown 格式分别输出英文和中文的博客内容，并在天气部分填入今天的天气信息

location: "Hefei"
